# Generated by Django 5.2.15 on 2026-06-10 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0.0', max_length=40)),
                ('schema_version', models.CharField(default='1.0.0', max_length=40)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('generated_by', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('invalid', 'Invalid'), ('failed', 'Failed')], db_index=True, default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_manifest', to='catalog.episode')),
            ],
            options={
                'ordering': ['episode__drama__slug', 'episode__episode_number'],
            },
        ),
        migrations.CreateModel(
            name='InteractionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_key', models.CharField(max_length=120)),
                ('component', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('emotion', models.CharField(blank=True, max_length=80)),
                ('start_ms', models.PositiveIntegerField()),
                ('end_ms', models.PositiveIntegerField()),
                ('priority', models.FloatField(default=0.0)),
                ('highlight_reason', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='interactions.interactionmanifest')),
            ],
            options={
                'ordering': ['manifest', 'sort_order', 'start_ms'],
            },
        ),
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=160, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('at_ms', models.FloatField(default=0)),
                ('client_timestamp', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to='accounts.deviceuser')),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to='catalog.drama')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to='catalog.episode')),
                ('interaction_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='interactions.interactionpoint')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractionAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('bucket', models.CharField(default='all', max_length=80)),
                ('count', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='interactions.interactionpoint')),
            ],
        ),
        migrations.AddIndex(
            model_name='interactionpoint',
            index=models.Index(fields=['component', 'start_ms'], name='interaction_compone_1d7344_idx'),
        ),
        migrations.AddConstraint(
            model_name='interactionpoint',
            constraint=models.UniqueConstraint(fields=('manifest', 'point_key'), name='unique_point_key_per_manifest'),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['device_user', 'received_at'], name='interaction_device__a38855_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['drama', 'episode', 'received_at'], name='interaction_drama_i_de8b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['interaction_point', 'event_type'], name='interaction_interac_1a6b2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='interactionaggregate',
            constraint=models.UniqueConstraint(fields=('interaction_point', 'event_type', 'bucket'), name='unique_interaction_aggregate'),
        ),
    ]
