# Generated by Django 5.2.15 on 2026-06-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(max_length=80)),
                ('owner_id', models.CharField(max_length=80)),
                ('asset_type', models.CharField(choices=[('video', 'Video'), ('poster', 'Poster'), ('cover', 'Cover'), ('frame', 'Frame'), ('character', 'Character'), ('evidence', 'Evidence'), ('generated_image', 'Generated image'), ('lottie', 'Lottie'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('file', models.FileField(blank=True, upload_to='assets/')),
                ('url', models.URLField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_type', 'owner_id'], name='media_asset_owner_t_1dd94f_idx'), models.Index(fields=['asset_type', 'created_at'], name='media_asset_asset_t_7723e5_idx')],
            },
        ),
    ]
