# Generated by Django 5.2.15 on 2026-06-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('drama', 'Drama'), ('episode', 'Episode'), ('interaction_point', 'Interaction point')], db_index=True, max_length=40)),
                ('object_id', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('embedding_status', models.CharField(db_index=True, default='pending', max_length=40)),
                ('embedding_vector', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['object_type', 'updated_at'], name='search_sear_object__98ee3c_idx')],
                'constraints': [models.UniqueConstraint(fields=('object_type', 'object_id'), name='unique_search_document_object')],
            },
        ),
    ]
