# Generated by Django 5.2.15 on 2026-06-10 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('pending', 'Pending'), ('hidden', 'Hidden'), ('deleted', 'Deleted')], db_index=True, default='visible', max_length=24)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.deviceuser')),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.drama')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.episode')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['drama', 'episode', 'status', 'created_at'], name='comments_co_drama_i_775537_idx'), models.Index(fields=['device_user', 'created_at'], name='comments_co_device__64b7c7_idx')],
            },
        ),
    ]
