# Generated by Django 5.2.15 on 2026-06-10 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('published', 'Published'), ('archived', 'Archived'), ('failed', 'Failed')], db_index=True, default='draft', max_length=24)),
                ('genre_tags', models.JSONField(blank=True, default=list)),
                ('score_label', models.CharField(default='暂无评分', max_length=40)),
                ('heat_label', models.CharField(default='0 集', max_length=40)),
                ('poster', models.ImageField(blank=True, upload_to='posters/')),
                ('cover', models.ImageField(blank=True, upload_to='covers/')),
                ('source', models.CharField(default='admin', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('video_file', models.FileField(blank=True, upload_to='videos/')),
                ('source_video_path', models.CharField(blank=True, max_length=600)),
                ('video_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=24)),
                ('manifest_status', models.CharField(choices=[('missing', 'Missing'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='missing', max_length=24)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='catalog.drama')),
            ],
            options={
                'ordering': ['drama__slug', 'episode_number'],
                'constraints': [models.UniqueConstraint(fields=('drama', 'episode_number'), name='unique_episode_number_per_drama')],
            },
        ),
    ]
